version: "3.9"
services:
  db:
    image: mariadb:latest
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SUPER_AUTH}
      - MYSQL_DATABASE=${MYSQL_APP_DB}
      - MYSQL_USER=${MYSQL_APP_USER}
      - MYSQL_PASSWORD=${MYSQL_APP_AUTH}
    container_name: ${APP_DOMAIN}_db
    hostname: db.${APP_DOMAIN}
  wordpress:
    image: wordpress
    container_name: ${APP_DOMAIN}_wp
    ports:
      - ${APP_PORT}:80
    restart: always
    volumes:
      - site_data:/var/www/html
      - php_config:/usr/local/etc/php
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_APP_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_APP_AUTH}
      - WORDPRESS_DB_NAME=${MYSQL_APP_DB}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - HTTP_X_FORWARDED_PROTO=https
  wpcli:
    container_name: ${APP_DOMAIN}_cli
    depends_on:
      - wordpress
    image: wordpress:cli
    user: ${HOST_USER}:${HOST_GROUP}
    command: tail -f /dev/null
    volumes:
      - site_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_APP_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_APP_AUTH}
      - WORDPRESS_DB_NAME=${MYSQL_APP_DB}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
  sftp:
    image: atmoz/sftp
    container_name: ${APP_DOMAIN}_sftp
    volumes:
      - site_data:/home/${SFTP_USER}/www
    ports:
      - ${SFTP_PORT}:22
    command: ${SFTP_USER}:${SFTP_USER_AUTH}:${HOST_USER}:${HOST_GROUP}:www
volumes:
  db_data:
  site_data:
  php_config:
